/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HandlersCreateHomeRequest
 */
export interface HandlersCreateHomeRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'country': string;
    /**
     * 
     * @type {number}
     * @memberof HandlersCreateHomeRequest
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof HandlersCreateHomeRequest
     */
    'longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'postal_code': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateHomeRequest
     */
    'province': string;
}

