/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsUser
 */
export interface ModelsUser {
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'default_home_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'id'?: string;
    /**
     * user, admin, support
     * @type {string}
     * @memberof ModelsUser
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUser
     */
    'updatedAt'?: string;
}

