/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HandlersOTPVerifyRequest
 */
export interface HandlersOTPVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersOTPVerifyRequest
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof HandlersOTPVerifyRequest
     */
    'email': string;
}

