/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HandlersSetDefaultHomeRequest
 */
export interface HandlersSetDefaultHomeRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersSetDefaultHomeRequest
     */
    'home_id': string;
}

