/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for Google mobile login (ID token from the client).
 * @export
 * @interface HandlersGoogleMobileRequest
 */
export interface HandlersGoogleMobileRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleMobileRequest
     */
    'id_token': string;
}

