/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsUser } from './models-user';

/**
 * 
 * @export
 * @interface HandlersAuthResponse
 */
export interface HandlersAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersAuthResponse
     */
    'token'?: string;
    /**
     * 
     * @type {ModelsUser}
     * @memberof HandlersAuthResponse
     */
    'user'?: ModelsUser;
}

