/* tslint:disable */
/* eslint-disable */
/**
 * GroceMate API
 * This is the API for GroceMate backend.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsHome
 */
export interface ModelsHome {
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsHome
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsHome
     */
    'longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'ownerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'postalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'province'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsHome
     */
    'updatedAt'?: string;
}

